### PR TITLE
- Migrated to sound null-safety

### PR DESCRIPTION
**Pull request by dokumanx**
I had to use this package in my current project. So, I have migrated it to sound null-safety.

### CODE REVIEW

**Comment by benPesso** [comment]
I was badly procrastinating with this one, so thank you! 😇😄

**Comment by dokumanx** [comment]
You're welcome 😄

**Comment by benPesso** [comment]
FYI, your changes ended up forcing me to go over the code and refactor it, which I guess is a good thing, as I took the opportunity to update the code with the latest version from Flutter. :)

**Comment by dokumanx** [comment]
I guess I'm glad to hear it😄 Hope to not force you to do unwanted work load.

**Pull request merged**
